baseURL = '/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'My New Hugo Project'
cleanDestinationDir = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  state    = "states"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "A production-ready Hugo site built with best practices."
  [params.social]
    twitter = "yourtwitterhandle"
    github  = "anand-raj"

[[menus.main]]
  name       = "Articles"
  identifier = "menu_articles"
  url        = "/articles/"
  weight     = 10

[[menus.main]]
  name       = "News"
  identifier = "menu_news"
  url        = "/news/"
  weight     = 30

[[menus.main]]
  name       = "About"
  identifier = "menu_about"
  url        = "/about/"
  weight     = 50

